server:
  servlet:
    port:  8080
    contextPath: api

spring:
  application:
    name: proman-api

  datasource:
    url: jdbc:postgresql://locahost:5432/postgres
    username: postgres
    password: admin

  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        database_platform: org.hibernate.dialect.PostgresSQL9Dialect